name:                multipool
version:             0.1.0.0
github:              "iand675/multipool"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "2018 Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/multipool#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- resource-pool
- persistent
- text
- hashable
- unliftio-core
- unordered-containers
# Todo move these out
- bytestring
- persistent-postgresql
- monad-logger
- hedis
- mmorph

library:
  source-dirs: src

tests:
  multipool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multipool
