name:                multipool-persistent-postgresql
version:             0.2.0.0
github:              "iand675/multipool-persistent-postgresql"
license:             BSD3
author:              "Ian Duncan"
maintainer:          "ian@iankduncan.com"
copyright:           "Ian Duncan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Read and write appropriately from both master and replicated postgresql instances.
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/multipool#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- multipool
- multipool-persistent
- postgresql-common-persistent
- unliftio-core
- monad-logger
- persistent >= 2.9.0
- persistent-postgresql >= 2.9.0
- persistent-qq
- unordered-containers

library:
  source-dirs: src

tests:
  multipool-persistent-postgresql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multipool-persistent-postgresql
